"""
Anchor update — 12 cidades (exceto Goiânia, já feita)
Regra: verbo de intenção sempre presente (aluguel/locação/alugar/locar)
Zonas protegidas: <header> e .ft__col
"""

import re
import os

BASE = "/Users/jrios/move-maquinas-seo"

# ---------------------------------------------------------------------------
# Polos por cidade (fonte: city-context-database.json)
# ---------------------------------------------------------------------------
# aparecida-de-goiania-go: DAIAG, DIMAG
# anapolis-go: DAIA, Porto Seco
# senador-canedo-go: DASC, Complexo Petroquímico
# brasilia-df: SIA, Ceilândia Industrial
# luziania-go: DIAL
# trindade-go: Polo Industrial de Trindade
# inhumas-go: Distrito Industrial de Inhumas
# itumbiara-go: Polo Sucroalcooleiro
# caldas-novas-go: Polo Hoteleiro / Turístico
# formosa-go: Polo Agropecuário
# uruacu-go: Polo Agropecuário Norte
# valparaiso-de-goias-go: Polo Moveleiro (120 fábricas)

# ---------------------------------------------------------------------------
# APARECIDA DE GOIÂNIA
# ---------------------------------------------------------------------------
APARECIDA = {
    "index.html": [
        ("/goiania-go/",
         "Goiânia (8 km)",
         "aluguel de equipamentos em Goiânia GO"),
        ("/senador-canedo-go/",
         "Senador Canedo (15 km)",
         "locação de máquinas no DASC Senador Canedo"),
        ("/trindade-go/",
         "Trindade (28 km)",
         "aluguel de empilhadeira em Trindade GO"),
        ("/anapolis-go/",
         "Anápolis (60 km)",
         "locação de equipamentos no DAIA Anápolis"),
        ("/inhumas-go/",
         "Inhumas (45 km)",
         "aluguel de máquinas em Inhumas GO"),
        ("/brasilia-df/",
         "Brasília (210 km)",
         "locação de equipamentos pesados em Brasília DF"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/aparecida-de-goiania-go/",
         "Equipamentos em Aparecida de Goiânia",
         "locação de equipamentos em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no DAIAG Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada no DIMAG Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Aparecida de Goiânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Goiânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Aparecida de Goiânia"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Move Máquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/aparecida-de-goiania-go/",
         "Equipamentos em Aparecida de Goiânia",
         "locação de equipamentos em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no DAIAG Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no DIMAG Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Aparecida GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Aparecida de Goiânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Move Máquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/aparecida-de-goiania-go/",
         "Equipamentos em Aparecida de Goiânia",
         "locação de equipamentos em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada no DIMAG Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark no DAIAG Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica para armazém em Aparecida GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Aparecida de Goiânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Aparecida GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Move Máquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/aparecida-de-goiania-go/",
         "Equipamentos em Aparecida de Goiânia",
         "locação de equipamentos em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada no DIMAG Aparecida GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Aparecida GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Move Máquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/aparecida-de-goiania-go/",
         "Equipamentos em Aparecida de Goiânia",
         "aluguel de equipamentos em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Aparecida de Goiânia"),
        ("/aparecida-de-goiania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica no DAIAG Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Aparecida GO"),
        ("/aparecida-de-goiania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Aparecida de Goiânia GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Move Máquinas",
         "ver equipamentos para locação em Aparecida GO"),
    ],
}

# ---------------------------------------------------------------------------
# ANÁPOLIS
# ---------------------------------------------------------------------------
ANAPOLIS = {
    "index.html": [
        ("/goiania-go/",
         "Goiânia (55 km)",
         "aluguel de equipamentos em Goiânia GO"),
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiânia (60 km)",
         "locação de máquinas no DAIAG Aparecida de Goiânia"),
        ("/inhumas-go/",
         "Inhumas (70 km)",
         "aluguel de empilhadeira em Inhumas GO"),
        ("/brasilia-df/",
         "Brasília (145 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
        ("/luziania-go/",
         "Luziânia (140 km)",
         "aluguel de máquinas no DIAL Luziânia GO"),
        ("/formosa-go/",
         "Formosa (180 km)",
         "locação de equipamentos em Formosa GO"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/anapolis-go/",
         "Equipamentos em Anápolis",
         "locação de equipamentos em Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Porto Seco Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada no DAIA Anápolis GO"),
        ("/anapolis-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica para depósito em Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira no DAIA Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Anápolis GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/anapolis-go/",
         "Equipamentos em Anápolis",
         "locação de equipamentos em Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no Porto Seco Anápolis"),
        ("/anapolis-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no DAIA Anápolis GO"),
        ("/anapolis-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Anápolis"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/anapolis-go/",
         "Equipamentos em Anápolis",
         "locação de equipamentos em Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para fachada no DAIA Anápolis"),
        ("/anapolis-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark no Porto Seco Anápolis"),
        ("/anapolis-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica para armazém em Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Anápolis GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Anápolis"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/anapolis-go/",
         "Equipamentos em Anápolis",
         "locação de equipamentos em Anápolis"),
        ("/anapolis-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa no DAIA Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Anápolis GO"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Anápolis GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Anápolis"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/anapolis-go/",
         "Equipamentos em Anápolis",
         "aluguel de equipamentos em Anápolis GO"),
        ("/anapolis-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Anápolis GO"),
        ("/anapolis-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para depósito no DAIA Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Anápolis"),
        ("/anapolis-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Anápolis GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Anápolis GO"),
    ],
}

# ---------------------------------------------------------------------------
# SENADOR CANEDO
# ---------------------------------------------------------------------------
SENADOR_CANEDO = {
    "index.html": [
        ("/goiania-go/",
         "Goiania (20 km)",
         "aluguel de equipamentos em Goiânia GO"),
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiania (25 km)",
         "locação de máquinas no DAIAG Aparecida de Goiânia"),
        ("/trindade-go/",
         "Trindade (35 km)",
         "aluguel de empilhadeira em Trindade GO"),
        ("/anapolis-go/",
         "Anapolis (130 km)",
         "locação de equipamentos no DAIA Anápolis"),
        ("/inhumas-go/",
         "Inhumas (60 km)",
         "aluguel de máquinas em Inhumas GO"),
        ("/brasilia-df/",
         "Brasilia (225 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/senador-canedo-go/",
         "Equipamentos em Senador Canedo",
         "locação de equipamentos em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no DASC Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada no Complexo Petroquímico Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica no DASC Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Senador Canedo"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/senador-canedo-go/",
         "Equipamentos em Senador Canedo",
         "locação de equipamentos em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no DASC Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Complexo Petroquímico Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Senador Canedo"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/senador-canedo-go/",
         "Equipamentos em Senador Canedo",
         "locação de equipamentos em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada no DASC Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark no Complexo Petroquímico Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Senador Canedo"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/senador-canedo-go/",
         "Equipamentos em Senador Canedo",
         "locação de equipamentos em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no DASC Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Senador Canedo GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Senador Canedo"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/senador-canedo-go/",
         "Equipamentos em Senador Canedo",
         "aluguel de equipamentos em Senador Canedo GO"),
        ("/senador-canedo-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no DASC Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica no Complexo Petroquímico Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Senador Canedo"),
        ("/senador-canedo-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Senador Canedo GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Senador Canedo"),
    ],
}

# ---------------------------------------------------------------------------
# BRASÍLIA DF
# ---------------------------------------------------------------------------
BRASILIA = {
    "index.html": [
        ("/luziania-go/",
         "Luziania (60 km)",
         "aluguel de equipamentos no DIAL Luziânia GO"),
        ("/valparaiso-de-goias-go/",
         "Valparaiso de Goias (35 km)",
         "locação de máquinas no Polo Moveleiro Valparaíso GO"),
        ("/formosa-go/",
         "Formosa (80 km)",
         "aluguel de empilhadeira em Formosa GO"),
        ("/goiania-go/",
         "Goiania (209 km, sede)",
         "locação de equipamentos em Goiânia GO"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/brasilia-df/",
         "Equipamentos em Brasília",
         "locação de equipamentos em Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no SIA Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada na Ceilândia Industrial Brasília"),
        ("/brasilia-df/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica no SIA Brasília"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Brasília DF"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/brasilia-df/",
         "Equipamentos em Brasília",
         "locação de equipamentos em Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no SIA Brasília DF"),
        ("/brasilia-df/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark na Ceilândia Industrial DF"),
        ("/brasilia-df/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Brasília"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/brasilia-df/",
         "Equipamentos em Brasília",
         "locação de equipamentos em Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada no SIA Brasília DF"),
        ("/brasilia-df/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark na Ceilândia Industrial Brasília"),
        ("/brasilia-df/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Brasília"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/brasilia-df/",
         "Equipamentos em Brasília",
         "locação de equipamentos em Brasília DF"),
        ("/brasilia-df/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa no SIA Brasília"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Brasília DF"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Brasília"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/brasilia-df/",
         "Equipamentos em Brasília",
         "aluguel de equipamentos em Brasília DF"),
        ("/brasilia-df/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no SIA Brasília DF"),
        ("/brasilia-df/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica na Ceilândia Industrial Brasília"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Brasília DF"),
        ("/brasilia-df/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Brasília DF"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Brasília DF"),
    ],
}

# ---------------------------------------------------------------------------
# LUZIÂNIA
# ---------------------------------------------------------------------------
LUZIANIA = {
    "index.html": [
        ("/brasilia-df/",
         "Brasilia (58 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
        ("/valparaiso-de-goias-go/",
         "Valparaiso de Goias (30 km)",
         "aluguel de máquinas no Polo Moveleiro Valparaíso GO"),
        ("/formosa-go/",
         "Formosa (130 km)",
         "aluguel de empilhadeira em Formosa GO"),
        ("/goiania-go/",
         "Goiania (198 km, sede)",
         "locação de equipamentos em Goiânia GO"),
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiania (190 km)",
         "aluguel de equipamentos no DAIAG Aparecida de Goiânia"),
        ("/anapolis-go/",
         "Anapolis (270 km)",
         "locação de máquinas no DAIA Anápolis GO"),
        ("/senador-canedo-go/",
         "Senador Canedo (180 km)",
         "aluguel de empilhadeira no DASC Senador Canedo"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/luziania-go/",
         "Equipamentos em Luziânia",
         "locação de equipamentos em Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no DIAL Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Luziânia GO"),
        ("/luziania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica no DIAL Luziânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Luziânia GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/luziania-go/",
         "Equipamentos em Luziânia",
         "locação de equipamentos em Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no DIAL Luziânia GO"),
        ("/luziania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Luziânia GO"),
        ("/luziania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Luziânia"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/luziania-go/",
         "Equipamentos em Luziânia",
         "locação de equipamentos em Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para fachada em Luziânia GO"),
        ("/luziania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark no DIAL Luziânia"),
        ("/luziania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Luziânia"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/luziania-go/",
         "Equipamentos em Luziânia",
         "locação de equipamentos em Luziânia GO"),
        ("/luziania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa no DIAL Luziânia"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Luziânia GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Luziânia"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/luziania-go/",
         "Equipamentos em Luziânia",
         "aluguel de equipamentos em Luziânia GO"),
        ("/luziania-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no DIAL Luziânia GO"),
        ("/luziania-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica em Luziânia GO"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Luziânia"),
        ("/luziania-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Luziânia GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Luziânia GO"),
    ],
}

# ---------------------------------------------------------------------------
# TRINDADE
# ---------------------------------------------------------------------------
TRINDADE = {
    "index.html": [
        ("/goiania-go/",
         "Goiania (18 km)",
         "aluguel de equipamentos em Goiânia GO"),
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiania (28 km)",
         "locação de máquinas no DAIAG Aparecida de Goiânia"),
        ("/senador-canedo-go/",
         "Senador Canedo (38 km)",
         "aluguel de empilhadeira no DASC Senador Canedo"),
        ("/inhumas-go/",
         "Inhumas (22 km)",
         "locação de máquinas em Inhumas GO"),
        ("/anapolis-go/",
         "Anapolis (70 km)",
         "aluguel de equipamentos no DAIA Anápolis"),
        ("/brasilia-df/",
         "Brasilia (225 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/trindade-go/",
         "Equipamentos em Trindade",
         "locação de equipamentos em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Industrial de Trindade"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Trindade GO"),
        ("/trindade-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Trindade GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/trindade-go/",
         "Equipamentos em Trindade",
         "locação de equipamentos em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Trindade GO"),
        ("/trindade-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Industrial de Trindade"),
        ("/trindade-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Trindade"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/trindade-go/",
         "Equipamentos em Trindade",
         "locação de equipamentos em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para fachada em Trindade GO"),
        ("/trindade-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Trindade GO"),
        ("/trindade-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Trindade"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/trindade-go/",
         "Equipamentos em Trindade",
         "locação de equipamentos em Trindade GO"),
        ("/trindade-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Trindade GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Trindade"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/trindade-go/",
         "Equipamentos em Trindade",
         "aluguel de equipamentos em Trindade GO"),
        ("/trindade-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Trindade GO"),
        ("/trindade-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica no Polo Industrial de Trindade"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Trindade GO"),
        ("/trindade-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Trindade GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Trindade GO"),
    ],
}

# ---------------------------------------------------------------------------
# INHUMAS
# Nota: hub de inhumas tinha links errados (copiou de aparecida), mas
# atualizamos para os textos que existem no HTML real
# ---------------------------------------------------------------------------
INHUMAS = {
    "index.html": [
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiânia (8 km)",
         "locação de máquinas no DAIAG Aparecida de Goiânia"),
        ("/senador-canedo-go/",
         "Senador Canedo (18 km)",
         "aluguel de empilhadeira no DASC Senador Canedo"),
        ("/trindade-go/",
         "Trindade (25 km)",
         "locação de equipamentos em Trindade GO"),
        ("/anapolis-go/",
         "Anápolis (55 km)",
         "aluguel de equipamentos no DAIA Anápolis GO"),
        ("/inhumas-go/",
         "Inhumas (40 km)",
         "aluguel de equipamentos em Inhumas GO"),
        ("/brasilia-df/",
         "Brasília (209 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/inhumas-go/",
         "Equipamentos em Inhumas",
         "locação de equipamentos em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Distrito Industrial de Inhumas"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Inhumas GO"),
        ("/inhumas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Inhumas GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/inhumas-go/",
         "Equipamentos em Inhumas",
         "locação de equipamentos em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Inhumas GO"),
        ("/inhumas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Distrito Industrial de Inhumas"),
        ("/inhumas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Inhumas"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/inhumas-go/",
         "Equipamentos em Inhumas",
         "locação de equipamentos em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para fachada em Inhumas GO"),
        ("/inhumas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Inhumas GO"),
        ("/inhumas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Inhumas"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/inhumas-go/",
         "Equipamentos em Inhumas",
         "locação de equipamentos em Inhumas GO"),
        ("/inhumas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Inhumas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Inhumas"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/inhumas-go/",
         "Equipamentos em Inhumas",
         "aluguel de equipamentos em Inhumas GO"),
        ("/inhumas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Inhumas GO"),
        ("/inhumas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica no Distrito Industrial de Inhumas"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Inhumas GO"),
        ("/inhumas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Inhumas GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Inhumas GO"),
    ],
}

# ---------------------------------------------------------------------------
# ITUMBIARA
# ---------------------------------------------------------------------------
ITUMBIARA = {
    "index.html": [
        ("/caldas-novas-go/",
         "Caldas Novas (160 km)",
         "aluguel de equipamentos em Caldas Novas GO"),
        ("/goiania-go/",
         "Goiania (203 km, sede)",
         "locação de equipamentos em Goiânia GO"),
        ("/anapolis-go/",
         "Anapolis (260 km)",
         "aluguel de máquinas no DAIA Anápolis GO"),
        ("/senador-canedo-go/",
         "Senador Canedo (220 km)",
         "locação de empilhadeira no DASC Senador Canedo"),
        ("/brasilia-df/",
         "Brasilia (480 km)",
         "aluguel de equipamentos pesados no SIA Brasília DF"),
        ("/luziania-go/",
         "Luziania (340 km)",
         "locação de máquinas no DIAL Luziânia GO"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/itumbiara-go/",
         "Equipamentos em Itumbiara",
         "locação de equipamentos em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Sucroalcooleiro Itumbiara"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Itumbiara GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/itumbiara-go/",
         "Equipamentos em Itumbiara",
         "locação de equipamentos em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Sucroalcooleiro Itumbiara"),
        ("/itumbiara-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Itumbiara"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/itumbiara-go/",
         "Equipamentos em Itumbiara",
         "locação de equipamentos em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Itumbiara"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/itumbiara-go/",
         "Equipamentos em Itumbiara",
         "locação de equipamentos em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Itumbiara GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Itumbiara"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/itumbiara-go/",
         "Equipamentos em Itumbiara",
         "aluguel de equipamentos em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Sucroalcooleiro Itumbiara"),
        ("/itumbiara-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Itumbiara GO"),
        ("/itumbiara-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Itumbiara GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Itumbiara GO"),
    ],
}

# ---------------------------------------------------------------------------
# CALDAS NOVAS (hub copiou links de aparecida — corrigir para caldas)
# ---------------------------------------------------------------------------
CALDAS_NOVAS = {
    "index.html": [
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiânia (8 km)",
         "locação de máquinas no DAIAG Aparecida de Goiânia"),
        ("/senador-canedo-go/",
         "Senador Canedo (18 km)",
         "aluguel de empilhadeira no DASC Senador Canedo"),
        ("/trindade-go/",
         "Trindade (25 km)",
         "locação de equipamentos em Trindade GO"),
        ("/anapolis-go/",
         "Anápolis (55 km)",
         "aluguel de equipamentos no DAIA Anápolis GO"),
        ("/inhumas-go/",
         "Inhumas (40 km)",
         "aluguel de máquinas em Inhumas GO"),
        ("/brasilia-df/",
         "Brasília (209 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/caldas-novas-go/",
         "Equipamentos em Caldas Novas",
         "locação de equipamentos em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Hoteleiro Caldas Novas"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Caldas Novas GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/caldas-novas-go/",
         "Equipamentos em Caldas Novas",
         "locação de equipamentos em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Hoteleiro Caldas Novas"),
        ("/caldas-novas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Caldas Novas"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/caldas-novas-go/",
         "Equipamentos em Caldas Novas",
         "locação de equipamentos em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Caldas Novas"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/caldas-novas-go/",
         "Equipamentos em Caldas Novas",
         "locação de equipamentos em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Caldas Novas GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Caldas Novas"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/caldas-novas-go/",
         "Equipamentos em Caldas Novas",
         "aluguel de equipamentos em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica no Polo Hoteleiro Caldas Novas"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Caldas Novas GO"),
        ("/caldas-novas-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Caldas Novas GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Caldas Novas GO"),
    ],
}

# ---------------------------------------------------------------------------
# FORMOSA
# ---------------------------------------------------------------------------
FORMOSA = {
    "index.html": [
        ("/brasilia-df/",
         "Brasilia (80 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
        ("/luziania-go/",
         "Luziania (150 km)",
         "aluguel de máquinas no DIAL Luziânia GO"),
        ("/goiania-go/",
         "Goiania (280 km)",
         "locação de equipamentos em Goiânia GO"),
        ("/anapolis-go/",
         "Anapolis (230 km)",
         "aluguel de equipamentos no DAIA Anápolis GO"),
        ("/senador-canedo-go/",
         "Senador Canedo (290 km)",
         "locação de empilhadeira no DASC Senador Canedo"),
        ("/trindade-go/",
         "Trindade (300 km)",
         "aluguel de máquinas em Trindade GO"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/formosa-go/",
         "Equipamentos em Formosa",
         "locação de equipamentos em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Agropecuário Formosa"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Formosa GO"),
        ("/formosa-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Formosa GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/formosa-go/",
         "Equipamentos em Formosa",
         "locação de equipamentos em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Formosa GO"),
        ("/formosa-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Agropecuário Formosa"),
        ("/formosa-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Formosa"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/formosa-go/",
         "Equipamentos em Formosa",
         "locação de equipamentos em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Formosa GO"),
        ("/formosa-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Formosa GO"),
        ("/formosa-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Formosa"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/formosa-go/",
         "Equipamentos em Formosa",
         "locação de equipamentos em Formosa GO"),
        ("/formosa-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Formosa GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Formosa"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/formosa-go/",
         "Equipamentos em Formosa",
         "aluguel de equipamentos em Formosa GO"),
        ("/formosa-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Agropecuário Formosa"),
        ("/formosa-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Formosa GO"),
        ("/formosa-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Formosa GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Formosa GO"),
    ],
}

# ---------------------------------------------------------------------------
# URUAÇU
# ---------------------------------------------------------------------------
URUACU = {
    "index.html": [
        ("/uruacu-go/",
         "Uruacu",
         "aluguel de equipamentos em Uruaçu GO"),
        ("/goiania-go/",
         "Goiania (280 km)",
         "locação de equipamentos em Goiânia GO"),
        ("/anapolis-go/",
         "Anapolis (225 km)",
         "aluguel de máquinas no DAIA Anápolis GO"),
        ("/itumbiara-go/",
         "Itumbiara (480 km)",
         "locação de empilhadeira em Itumbiara GO"),
        ("/caldas-novas-go/",
         "Caldas Novas (410 km)",
         "aluguel de equipamentos em Caldas Novas GO"),
        ("/brasilia-df/",
         "Brasilia (490 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
        ("/senador-canedo-go/",
         "Senador Canedo (298 km)",
         "aluguel de empilhadeira no DASC Senador Canedo"),
        ("/inhumas-go/",
         "Inhumas (240 km)",
         "locação de máquinas em Inhumas GO"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/uruacu-go/",
         "Equipamentos em Uruaçu",
         "locação de equipamentos em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Agropecuário Norte GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Uruaçu GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/uruacu-go/",
         "Equipamentos em Uruaçu",
         "locação de equipamentos em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Agropecuário Norte GO"),
        ("/uruacu-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Uruaçu"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/uruacu-go/",
         "Equipamentos em Uruaçu",
         "locação de equipamentos em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Uruaçu"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/uruacu-go/",
         "Equipamentos em Uruaçu",
         "locação de equipamentos em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Uruaçu GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Uruaçu"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/uruacu-go/",
         "Equipamentos em Uruaçu",
         "aluguel de equipamentos em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Agropecuário Norte GO"),
        ("/uruacu-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Uruaçu GO"),
        ("/uruacu-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Uruaçu GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Uruaçu GO"),
    ],
}

# ---------------------------------------------------------------------------
# VALPARAÍSO DE GOIÁS
# ---------------------------------------------------------------------------
VALPARAISO = {
    "index.html": [
        ("/brasilia-df/",
         "Brasília (40 km)",
         "locação de equipamentos pesados no SIA Brasília DF"),
        ("/luziania-go/",
         "Luziânia (50 km)",
         "aluguel de máquinas no DIAL Luziânia GO"),
        ("/formosa-go/",
         "Formosa (95 km)",
         "aluguel de equipamentos em Formosa GO"),
        ("/goiania-go/",
         "Goiânia (230 km)",
         "locação de equipamentos em Goiânia GO"),
        ("/aparecida-de-goiania-go/",
         "Aparecida de Goiânia (225 km)",
         "aluguel de máquinas no DAIAG Aparecida de Goiânia"),
        ("/senador-canedo-go/",
         "Senador Canedo (215 km)",
         "locação de empilhadeira no DASC Senador Canedo"),
    ],
    "aluguel-de-empilhadeira-combustao/index.html": [
        ("/valparaiso-de-goias-go/",
         "Equipamentos em Valparaíso de Goiás",
         "locação de equipamentos em Valparaíso de Goiás GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "locação de plataforma tesoura no Polo Moveleiro Valparaíso GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "alugar plataforma articulada em Valparaíso de Goiás"),
        ("/valparaiso-de-goias-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira elétrica no Polo Moveleiro Valparaíso"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Valparaíso GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador em Valparaíso de Goiás"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de empilhadeira"),
    ],
    "aluguel-de-plataforma-elevatoria-articulada/index.html": [
        ("/valparaiso-de-goias-go/",
         "Equipamentos em Valparaíso de Goiás",
         "locação de equipamentos em Valparaíso de Goiás GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "alugar plataforma tesoura no Polo Moveleiro Valparaíso GO"),
        ("/valparaiso-de-goias-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark em Valparaíso de Goiás"),
        ("/valparaiso-de-goias-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira para galpão em Valparaíso GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Valparaíso de Goiás"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-35 e NR-11 para locação segura em Valparaíso"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma articulada"),
    ],
    "aluguel-de-plataforma-elevatoria-tesoura/index.html": [
        ("/valparaiso-de-goias-go/",
         "Equipamentos em Valparaíso de Goiás",
         "locação de equipamentos em Valparaíso de Goiás GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada em Valparaíso de Goiás"),
        ("/valparaiso-de-goias-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "aluguel de empilhadeira Clark no Polo Moveleiro Valparaíso"),
        ("/valparaiso-de-goias-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "locação de transpaleteira para armazém em Valparaíso GO"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operadores em Valparaíso de Goiás"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira em Valparaíso"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de plataforma tesoura"),
    ],
    "aluguel-de-transpaleteira/index.html": [
        ("/valparaiso-de-goias-go/",
         "Equipamentos em Valparaíso de Goiás",
         "locação de equipamentos em Valparaíso de Goiás GO"),
        ("/valparaiso-de-goias-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark para empresa em Valparaíso GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura para obra em Valparaíso GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada no Polo Moveleiro Valparaíso"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso Operador de Empilhadeira",
         "habilitação NR-11 para operador de empilhadeira em Valparaíso"),
        ("/goiania-go/curso-de-operador-de-empilhadeira",
         "Curso de Operador de Empilhadeira",
         "treinamento NR-11 para operador de empilhadeira"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver todas as cidades com locação de transpaleteira"),
    ],
    "curso-de-operador-de-empilhadeira/index.html": [
        ("/valparaiso-de-goias-go/",
         "Equipamentos em Valparaíso de Goiás",
         "aluguel de equipamentos em Valparaíso de Goiás GO"),
        ("/valparaiso-de-goias-go/aluguel-de-empilhadeira-combustao",
         "Empilhadeira",
         "locação de empilhadeira Clark no Polo Moveleiro Valparaíso"),
        ("/valparaiso-de-goias-go/aluguel-de-transpaleteira",
         "Transpaleteira Elétrica",
         "aluguel de transpaleteira elétrica em Valparaíso de Goiás"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-articulada",
         "Plataforma Articulada",
         "locação de plataforma articulada para obra em Valparaíso GO"),
        ("/valparaiso-de-goias-go/aluguel-de-plataforma-elevatoria-tesoura",
         "Plataforma Tesoura",
         "aluguel de plataforma tesoura em Valparaíso de Goiás GO"),
        ("/cidades-atendidas",
         "Cidades Atendidas",
         "cidades com disponibilidade de aluguel em GO e DF"),
        ("/cidades-atendidas",
         "Cidades atendidas pela Movemáquinas",
         "ver equipamentos para locação em Valparaíso de Goiás"),
    ],
}

# ---------------------------------------------------------------------------
# Mapa cidade → (slug, changes_dict)
# ---------------------------------------------------------------------------
CITY_MAP = {
    "aparecida-de-goiania-go": APARECIDA,
    "anapolis-go": ANAPOLIS,
    "senador-canedo-go": SENADOR_CANEDO,
    "brasilia-df": BRASILIA,
    "luziania-go": LUZIANIA,
    "trindade-go": TRINDADE,
    "inhumas-go": INHUMAS,
    "itumbiara-go": ITUMBIARA,
    "caldas-novas-go": CALDAS_NOVAS,
    "formosa-go": FORMOSA,
    "uruacu-go": URUACU,
    "valparaiso-de-goias-go": VALPARAISO,
}

# ---------------------------------------------------------------------------
# Engine (igual ao script de Goiânia)
# ---------------------------------------------------------------------------
NAV_PATTERN = re.compile(r'(<header\b[^>]*>.*?</header>)', re.DOTALL | re.IGNORECASE)
FOOTER_NAV_PATTERN = re.compile(r'(<div\s+class="[^"]*ft__col[^"]*"[^>]*>.*?</div>)', re.DOTALL | re.IGNORECASE)

def strip_zone(html, pattern):
    zones = []
    def replacer(m):
        idx = len(zones)
        zones.append(m.group(0))
        return f"__ZONE_{idx}__"
    return pattern.sub(replacer, html), zones

def restore_zones(html, zones):
    for idx, content in enumerate(zones):
        html = html.replace(f"__ZONE_{idx}__", content)
    return html

def make_link_pattern(href, old_text):
    h = re.escape(href)
    t = re.escape(old_text.strip())
    return re.compile(
        r'(<a\b[^>]*href=["\']' + h + r'["\'][^>]*>)\s*' + t + r'\s*(</a>)',
        re.IGNORECASE | re.DOTALL
    )

def make_link_pattern_with_span(href, old_text):
    h = re.escape(href)
    t = re.escape(old_text.strip())
    return re.compile(
        r'(<a\b[^>]*href=["\']' + h + r'["\'][^>]*>)'
        r'(<span[^>]*>.*?</span>)\s*' + t + r'\s*(</a>)',
        re.IGNORECASE | re.DOTALL
    )

def apply_changes(filepath, changes):
    with open(filepath, encoding="utf-8") as fh:
        original = fh.read()

    html = original
    applied = []
    skipped = []

    html, nav_zones = strip_zone(html, NAV_PATTERN)
    html, ft_zones = strip_zone(html, FOOTER_NAV_PATTERN)

    for href, old_text, new_text in changes:
        pat = make_link_pattern(href, old_text)
        match = pat.search(html)
        if match:
            html = pat.sub(f'{match.group(1)}{new_text}{match.group(2)}', html, count=1)
            applied.append((old_text, new_text))
            continue

        pat_span = make_link_pattern_with_span(href, old_text)
        match_span = pat_span.search(html)
        if match_span:
            html = pat_span.sub(
                lambda m: f'{m.group(1)}{m.group(2)}{new_text}{m.group(3)}',
                html, count=1
            )
            applied.append((old_text, new_text))
            continue

        skipped.append((href, old_text))

    html = restore_zones(html, nav_zones)
    html = restore_zones(html, ft_zones)

    if html != original:
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(html)

    return applied, skipped


# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
print("=" * 70)
print("ANCHOR UPDATE — 12 cidades (exceto Goiânia)")
print("Regra: verbo de intenção sempre presente")
print("=" * 70)

grand_applied = 0
grand_skipped = 0

for city_slug, changes_dict in CITY_MAP.items():
    city_base = os.path.join(BASE, city_slug)
    print(f"\n{'=' * 50}")
    print(f"CIDADE: {city_slug}")
    print(f"{'=' * 50}")

    city_applied = 0
    city_skipped = 0

    for rel_path, changes in changes_dict.items():
        filepath = os.path.join(city_base, rel_path)
        if not os.path.exists(filepath):
            print(f"  [ARQUIVO NAO ENCONTRADO] {rel_path}")
            continue

        applied, skipped = apply_changes(filepath, changes)
        city_applied += len(applied)
        city_skipped += len(skipped)

        page_label = rel_path.replace("/index.html", "") or "hub"
        print(f"\n  [{page_label}] aplicadas={len(applied)} nao_encontradas={len(skipped)}")
        for old, new in applied:
            print(f"    ANTES : {old}")
            print(f"    DEPOIS: {new}")
        for href, old in skipped:
            print(f"    ? [{old}] -> {href}")

    print(f"\n  SUBTOTAL {city_slug}: {city_applied} aplicadas | {city_skipped} nao encontradas")
    grand_applied += city_applied
    grand_skipped += city_skipped

print("\n" + "=" * 70)
print(f"GRAND TOTAL: {grand_applied} aplicadas | {grand_skipped} nao encontradas")
print("=" * 70)
